




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "DumpS2C_proxy.h"

namespace DumpS2C {


        
	bool Proxy::Dump_ChunkAck ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext )	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Dump_ChunkAck;
__msg.Write(__msgid); 
	
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_Dump_ChunkAck, (::Proud::RmiID)Rmi_Dump_ChunkAck);
	}

	bool Proxy::Dump_ChunkAck ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Dump_ChunkAck;
__msg.Write(__msgid); 
	
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_Dump_ChunkAck, (::Proud::RmiID)Rmi_Dump_ChunkAck);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_Dump_ChunkAck =_PNT("Dump_ChunkAck");
#else
const PNTCHAR* Proxy::RmiName_Dump_ChunkAck =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_Dump_ChunkAck;

}



