// argchk
#define crypt_argchk pn_crypt_argchk

// cfg
//#define XMALLOC pn_XMALLOC
//#define XREALLOC pn_XREALLOC
//#define XCALLOC pn_XCALLOC
//#define XFREE pn_XFREE
//#define XQSORT pn_XQSORT
//#define XCLOCK pn_XCLOCK
//#define XMEMCPY pn_XMEMCPY
//#define XMEMCMP pn_XMEMCMP
//#define XMEMSET pn_XMEMSET
//#define XSTRCMP pn_XSTRCMP

//ciper
#define blowfish_setup pn_blowfish_setup
#define blowfish_ecb_encrypt pn_blowfish_ecb_encrypt
#define blowfish_ecb_decrypt pn_blowfish_ecb_decrypt
#define blowfish_test pn_blowfish_test
#define blowfish_done pn_blowfish_done
#define blowfish_keysize pn_blowfish_keysize
#define rc5_setup pn_rc5_setup
#define rc5_ecb_encrypt pn_rc5_ecb_encrypt
#define rc5_ecb_decrypt pn_rc5_ecb_decrypt
#define rc5_test pn_rc5_test
#define rc5_done pn_rc5_done
#define rc5_keysize pn_rc5_keysize
#define rc6_setup pn_rc6_setup
#define rc6_ecb_encrypt pn_rc6_ecb_encrypt
#define rc6_ecb_decrypt pn_rc6_ecb_decrypt
#define rc6_test pn_rc6_test
#define rc6_done pn_rc6_done
#define rc6_keysize pn_rc6_keysize
#define rc2_setup pn_rc2_setup
#define rc2_ecb_encrypt pn_rc2_ecb_encrypt
#define rc2_ecb_decrypt pn_rc2_ecb_decrypt
#define rc2_test pn_rc2_test
#define rc2_done pn_rc2_done
#define rc2_keysize pn_rc2_keysize
#define saferp_setup pn_saferp_setup
#define saferp_ecb_encrypt pn_saferp_ecb_encrypt
#define saferp_ecb_decrypt pn_saferp_ecb_decrypt
#define saferp_test pn_saferp_test
#define saferp_done pn_saferp_done
#define saferp_keysize pn_saferp_keysize
#define safer_k64_setup pn_safer_k64_setup
#define safer_sk64_setup pn_safer_sk64_setup
#define safer_k128_setup pn_safer_k128_setup
#define safer_sk128_setup pn_safer_sk128_setup
#define safer_ecb_encrypt pn_safer_ecb_encrypt
#define safer_ecb_decrypt pn_safer_ecb_decrypt
#define safer_k64_test pn_safer_k64_test
#define safer_sk64_test pn_safer_sk64_test
#define safer_sk128_test pn_safer_sk128_test
#define safer_done pn_safer_done
#define safer_64_keysize pn_safer_64_keysize
#define safer_128_keysize pn_safer_128_keysize
#define rijndael_setup pn_rijndael_setup
#define rijndael_ecb_encrypt pn_rijndael_ecb_encrypt
#define rijndael_ecb_decrypt pn_rijndael_ecb_decrypt
#define rijndael_test pn_rijndael_test
#define rijndael_done pn_rijndael_done
#define rijndael_keysize pn_rijndael_keysize
#define rijndael_enc_setup pn_rijndael_enc_setup
#define rijndael_enc_ecb_encrypt pn_rijndael_enc_ecb_encrypt
#define rijndael_enc_done pn_rijndael_enc_done
#define rijndael_enc_keysize pn_rijndael_enc_keysize
#define xtea_setup pn_xtea_setup
#define xtea_ecb_encrypt pn_xtea_ecb_encrypt
#define xtea_ecb_decrypt pn_xtea_ecb_decrypt
#define xtea_test pn_xtea_test
#define xtea_done pn_xtea_done
#define xtea_keysize pn_xtea_keysize
#define twofish_setup pn_twofish_setup
#define twofish_ecb_encrypt pn_twofish_ecb_encrypt
#define twofish_ecb_decrypt pn_twofish_ecb_decrypt
#define twofish_test pn_twofish_test
#define twofish_done pn_twofish_done
#define twofish_keysize pn_twofish_keysize
#define des_setup pn_des_setup
#define des_ecb_encrypt pn_des_ecb_encrypt
#define des_ecb_decrypt pn_des_ecb_decrypt
#define des_test pn_des_test
#define des_done pn_des_done
#define des_keysize pn_des_keysize
#define des3_setup pn_des3_setup
#define des3_ecb_encrypt pn_des3_ecb_encrypt
#define des3_ecb_decrypt pn_des3_ecb_decrypt
#define des3_test pn_des3_test
#define des3_done pn_des3_done
#define des3_keysize pn_des3_keysize
#define cast5_setup pn_cast5_setup
#define cast5_ecb_encrypt pn_cast5_ecb_encrypt
#define cast5_ecb_decrypt pn_cast5_ecb_decrypt
#define cast5_test pn_cast5_test
#define cast5_done pn_cast5_done
#define cast5_keysize pn_cast5_keysize
#define noekeon_setup pn_noekeon_setup
#define noekeon_ecb_encrypt pn_noekeon_ecb_encrypt
#define noekeon_ecb_decrypt pn_noekeon_ecb_decrypt
#define noekeon_test pn_noekeon_test
#define noekeon_done pn_noekeon_done
#define noekeon_keysize pn_noekeon_keysize
#define skipjack_setup pn_skipjack_setup
#define skipjack_ecb_encrypt pn_skipjack_ecb_encrypt
#define skipjack_ecb_decrypt pn_skipjack_ecb_decrypt
#define skipjack_test pn_skipjack_test
#define skipjack_done pn_skipjack_done
#define skipjack_keysize pn_skipjack_keysize
#define khazad_setup pn_khazad_setup
#define khazad_ecb_encrypt pn_khazad_ecb_encrypt
#define khazad_ecb_decrypt pn_khazad_ecb_decrypt
#define khazad_test pn_khazad_test
#define khazad_done pn_khazad_done
#define khazad_keysize pn_khazad_keysize
#define anubis_setup pn_anubis_setup
#define anubis_ecb_encrypt pn_anubis_ecb_encrypt
#define anubis_ecb_decrypt pn_anubis_ecb_decrypt
#define anubis_test pn_anubis_test
#define anubis_done pn_anubis_done
#define anubis_keysize pn_anubis_keysize
#define kseed_setup pn_kseed_setup
#define kseed_ecb_encrypt pn_kseed_ecb_encrypt
#define kseed_ecb_decrypt pn_kseed_ecb_decrypt
#define kseed_test pn_kseed_test
#define kseed_done pn_kseed_done
#define kseed_keysize pn_kseed_keysize
#define kasumi_setup pn_kasumi_setup
#define kasumi_ecb_encrypt pn_kasumi_ecb_encrypt
#define kasumi_ecb_decrypt pn_kasumi_ecb_decrypt
#define kasumi_test pn_kasumi_test
#define kasumi_done pn_kasumi_done
#define kasumi_keysize pn_kasumi_keysize
#define multi2_setup pn_multi2_setup
#define multi2_ecb_encrypt pn_multi2_ecb_encrypt
#define multi2_ecb_decrypt pn_multi2_ecb_decrypt
#define multi2_test pn_multi2_test
#define multi2_done pn_multi2_done
#define multi2_keysize pn_multi2_keysize
#define ecb_start pn_ecb_start
#define ecb_encrypt pn_ecb_encrypt
#define ecb_decrypt pn_ecb_decrypt
#define ecb_done pn_ecb_done
#define cfb_start pn_cfb_start
#define cfb_encrypt pn_cfb_encrypt
#define cfb_decrypt pn_cfb_decrypt
#define cfb_getiv pn_cfb_getiv
#define cfb_setiv pn_cfb_setiv
#define cfb_done pn_cfb_done
#define ofb_start pn_ofb_start
#define ofb_encrypt pn_ofb_encrypt
#define ofb_decrypt pn_ofb_decrypt
#define ofb_getiv pn_ofb_getiv
#define ofb_setiv pn_ofb_setiv
#define ofb_done pn_ofb_done
#define cbc_start pn_cbc_start
#define cbc_encrypt pn_cbc_encrypt
#define cbc_decrypt pn_cbc_decrypt
#define cbc_getiv pn_cbc_getiv
#define cbc_setiv pn_cbc_setiv
#define cbc_done pn_cbc_done
#define ctr_start pn_ctr_start
#define ctr_encrypt pn_ctr_encrypt
#define ctr_decrypt pn_ctr_decrypt
#define ctr_getiv pn_ctr_getiv
#define ctr_setiv pn_ctr_setiv
#define ctr_done pn_ctr_done
#define ctr_test pn_ctr_test
#define lrw_start pn_lrw_start
#define lrw_encrypt pn_lrw_encrypt
#define lrw_decrypt pn_lrw_decrypt
#define lrw_getiv pn_lrw_getiv
#define lrw_setiv pn_lrw_setiv
#define lrw_done pn_lrw_done
#define lrw_test pn_lrw_test
#define lrw_process pn_lrw_process
#define f8_start pn_f8_start
#define f8_encrypt pn_f8_encrypt
#define f8_decrypt pn_f8_decrypt
#define f8_getiv pn_f8_getiv
#define f8_setiv pn_f8_setiv
#define f8_done pn_f8_done
#define f8_test_mode pn_f8_test_mode
#define xts_start pn_xts_start
#define xts_encrypt pn_xts_encrypt
#define xts_decrypt pn_xts_decrypt
#define xts_done pn_xts_done
#define xts_test pn_xts_test
#define xts_mult_x pn_xts_mult_x
#define find_cipher pn_find_cipher
#define find_cipher_any pn_find_cipher_any
#define find_cipher_id pn_find_cipher_id
#define register_cipher pn_register_cipher
#define unregister_cipher pn_unregister_cipher
#define cipher_is_valid pn_cipher_is_valid

#define setup_mixpn_setup_mix
#define setup_mix2pn_setup_mix2

// cipher-struct 
#define blowfish_key pn_blowfish_key
#define rc5_key pn_rc5_key
#define rc6_key pn_rc6_key
#define saferp_key pn_saferp_key
#define rijndael_key pn_rijndael_key
#define kseed_key pn_kseed_key
#define kasumi_key pn_kasumi_key
#define xtea_key pn_xtea_key
#define twofish_key pn_twofish_key
#define twofish_key pn_twofish_key
#define safer_block_t pn_safer_block_t
#define safer_key_t pn_safer_key_t
#define rc2_key  pn_rc2_key 
#define des_key  pn_des_key 
#define des3_key  pn_des3_key 
#define cast5_key pn_cast5_key
#define noekeon_key  pn_noekeon_key 
#define skipjack_key  pn_skipjack_key 
#define khazad_key  pn_khazad_key 
#define anubis_key  pn_anubis_key 
#define multi2_key  pn_multi2_key 
#define Symmetric_key  pn_Symmetric_key 
#define symmetric_key pn_symmetric_key
#define symmetric_ECB pn_symmetric_ECB
#define symmetric_CFB pn_symmetric_CFB
#define symmetric_OFB pn_symmetric_OFB
#define symmetric_CBC pn_symmetric_CBC
#define symmetric_CTR pn_symmetric_CTR
#define symmetric_LRW pn_symmetric_LRW
#define symmetric_F8 pn_symmetric_F8
#define ltc_cipher_descriptor  pn_ltc_cipher_descriptor 

#define blowfish_desc pn_blowfish_desc
#define rc5_desc pn_rc5_desc
#define rc6_desc pn_rc6_desc
#define rc2_desc pn_rc2_desc
#define saferp_desc pn_saferp_desc
#define safer_k64_desc pn_safer_k64_desc
#define safer_k128_desc pn_safer_k128_desc
#define safer_sk64_desc pn_safer_sk64_desc
#define safer_sk128_desc pn_safer_sk128_desc

#define rijndael_desc  pn_rijndael_desc 
#define cipher_descriptor pn_cipher_descriptor
#define aes_desc pn_aes_desc 
#define symmetric_xts pn_symmetric_xts
#define rijndael_enc_desc pn_rijndael_enc_desc 
#define aes_enc_desc pn_aes_enc_desc 

#define xtea_desc pn_xtea_desc
#define twofish_desc pn_twofish_desc
#define des_desc pn_des_desc
#define des3_desc pn_des3_desc
#define cast5_desc pn_cast5_desc
#define noekeon_desc pn_noekeon_desc
#define skipjack_desc pn_skipjack_desc
#define khazad_desc pn_khazad_desc
#define anubis_desc pn_anubis_desc
#define kseed_desc pn_kseed_desc
#define kasumi_desc pn_kasumi_desc
#define multi2_desc pn_multi2_desc

#define ltc_cipher_mutex pn_ltc_cipher_mutex


// hash
#define chc_register pn_chc_register
#define chc_init pn_chc_init
#define chc_process pn_chc_process
#define chc_done pn_chc_done
#define chc_test pn_chc_test
#define whirlpool_init pn_whirlpool_init
#define whirlpool_process pn_whirlpool_process
#define whirlpool_done pn_whirlpool_done
#define whirlpool_test pn_whirlpool_test
#define sha512_init pn_sha512_init
#define sha512_process pn_sha512_process
#define sha512_done pn_sha512_done
#define sha512_test pn_sha512_test
#define sha384_init pn_sha384_init
#define sha384_done pn_sha384_done
#define sha384_test pn_sha384_test
#define sha256_init pn_sha256_init
#define sha256_process pn_sha256_process
#define sha256_done pn_sha256_done
#define sha256_test pn_sha256_test
#define sha224_init pn_sha224_init
#define sha224_done pn_sha224_done
#define sha224_test pn_sha224_test
#define sha1_init pn_sha1_init
#define sha1_process pn_sha1_process
#define sha1_done pn_sha1_done
#define sha1_test pn_sha1_test
#define md5_init pn_md5_init
#define md5_process pn_md5_process
#define md5_done pn_md5_done
#define md5_test pn_md5_test
#define md4_init pn_md4_init
#define md4_process pn_md4_process
#define md4_done pn_md4_done
#define md4_test pn_md4_test
#define md2_init pn_md2_init
#define md2_process pn_md2_process
#define md2_done pn_md2_done
#define md2_test pn_md2_test
#define tiger_init pn_tiger_init
#define tiger_process pn_tiger_process
#define tiger_done pn_tiger_done
#define tiger_test pn_tiger_test
#define rmd128_init pn_rmd128_init
#define rmd128_process pn_rmd128_process
#define rmd128_done pn_rmd128_done
#define rmd128_test pn_rmd128_test
#define rmd160_init pn_rmd160_init
#define rmd160_process pn_rmd160_process
#define rmd160_done pn_rmd160_done
#define rmd160_test pn_rmd160_test
#define rmd256_init pn_rmd256_init
#define rmd256_process pn_rmd256_process
#define rmd256_done pn_rmd256_done
#define rmd256_test pn_rmd256_test
#define rmd320_init pn_rmd320_init
#define rmd320_process pn_rmd320_process
#define rmd320_done pn_rmd320_done
#define rmd320_test pn_rmd320_test
#define find_hash pn_find_hash
#define find_hash_id pn_find_hash_id
#define find_hash_oid pn_find_hash_oid
#define find_hash_any pn_find_hash_any
#define register_hash pn_register_hash
#define unregister_hash pn_unregister_hash
#define hash_is_valid pn_hash_is_valid
#define hash_memory pn_hash_memory
#define hash_memory_multi pn_hash_memory_multi
#define hash_filehandle pn_hash_filehandle
#define hash_file pn_hash_file

// hash-struct
#define sha512_state  pn_sha512_state 
#define sha256_state  pn_sha256_state 
#define sha1_state  pn_sha1_state 
#define md5_state  pn_md5_state 
#define md4_state  pn_md4_state 
#define tiger_state  pn_tiger_state 
#define md2_state  pn_md2_state 
#define rmd128_state  pn_rmd128_state 
#define rmd160_state  pn_rmd160_state 
#define rmd256_state  pn_rmd256_state 
#define rmd320_state  pn_rmd320_state 
#define whirlpool_state  pn_whirlpool_state 
#define chc_state  pn_chc_state 
#define Hash_state  pn_Hash_state 
#define hash_state pn_hash_state
#define ltc_hash_descriptor  pn_ltc_hash_descriptor 
#define hash_descriptor pn_hash_descriptor
#define ltc_hash_descriptor  pn_ltc_hash_descriptor 
#define chc_desc pn_chc_desc
#define whirlpool_desc pn_whirlpool_desc
#define sha512_desc pn_sha512_desc
#define sha384_desc pn_sha384_desc
#define sha256_desc pn_sha256_desc
#define sha224_desc pn_sha224_desc
#define sha1_desc pn_sha1_desc
#define md5_desc pn_md5_desc
#define md4_desc pn_md4_desc
#define md2_desc pn_md2_desc
#define tiger_desc pn_tiger_desc
#define rmd128_desc pn_rmd128_desc
#define rmd160_desc pn_rmd160_desc
#define rmd256_desc pn_rmd256_desc
#define rmd320_desc pn_rmd320_desc

#define ltc_hash_mutex pn_ltc_hash_mutex


// mac
#define hmac_init pn_hmac_init
#define hmac_process pn_hmac_process
#define hmac_done pn_hmac_done
#define hmac_test pn_hmac_test
#define hmac_memory pn_hmac_memory
#define hmac_memory_multi pn_hmac_memory_multi
#define hmac_file pn_hmac_file
#define omac_init pn_omac_init
#define omac_process pn_omac_process
#define omac_done pn_omac_done
#define omac_memory pn_omac_memory
#define omac_memory_multi pn_omac_memory_multi
#define omac_file pn_omac_file
#define omac_test pn_omac_test
#define pmac_init pn_pmac_init
#define pmac_process pn_pmac_process
#define pmac_done pn_pmac_done
#define pmac_memory pn_pmac_memory
#define pmac_memory_multi pn_pmac_memory_multi
#define pmac_file pn_pmac_file
#define pmac_test pn_pmac_test
#define pmac_ntz pn_pmac_ntz
#define pmac_shift_xor pn_pmac_shift_xor
#define eax_init pn_eax_init
#define eax_encrypt pn_eax_encrypt
#define eax_decrypt pn_eax_decrypt
#define eax_addheader pn_eax_addheader
#define eax_done pn_eax_done
#define eax_encrypt_authenticate_memory pn_eax_encrypt_authenticate_memory
#define eax_decrypt_verify_memory pn_eax_decrypt_verify_memory
#define eax_test pn_eax_test
#define ocb_init pn_ocb_init
#define ocb_encrypt pn_ocb_encrypt
#define ocb_decrypt pn_ocb_decrypt
#define ocb_done_encrypt pn_ocb_done_encrypt
#define ocb_done_decrypt pn_ocb_done_decrypt
#define ocb_encrypt_authenticate_memory pn_ocb_encrypt_authenticate_memory
#define ocb_decrypt_verify_memory pn_ocb_decrypt_verify_memory
#define ocb_test pn_ocb_test
#define ocb_shift_xor pn_ocb_shift_xor
#define ocb_ntz pn_ocb_ntz
#define s_ocb_done pn_s_ocb_done
#define ccm_memory pn_ccm_memory
#define ccm_test pn_ccm_test
#define gcm_gf_mult pn_gcm_gf_mult
#define gcm_mult_h pn_gcm_mult_h
#define gcm_init pn_gcm_init
#define gcm_reset pn_gcm_reset
#define gcm_add_iv pn_gcm_add_iv
#define gcm_add_aad pn_gcm_add_aad
#define gcm_process pn_gcm_process
#define gcm_done pn_gcm_done
#define burn_stack pn_burn_stack
#define error_to_string pn_error_to_string
#define gcm_memory pn_gcm_memory
#define gcm_test pn_gcm_test
#define pelican_init pn_pelican_init
#define pelican_process pn_pelican_process
#define pelican_done pn_pelican_done
#define pelican_test pn_pelican_test
#define pelican_memory pn_pelican_memory
#define xcbc_init pn_xcbc_init
#define xcbc_process pn_xcbc_process
#define xcbc_done pn_xcbc_done
#define xcbc_memory pn_xcbc_memory
#define xcbc_memory_multi pn_xcbc_memory_multi
#define xcbc_file pn_xcbc_file
#define xcbc_test pn_xcbc_test
#define f9_init pn_f9_init
#define f9_process pn_f9_process
#define f9_done pn_f9_done
#define f9_memory pn_f9_memory
#define f9_memory_multi pn_f9_memory_multi
#define f9_file pn_f9_file
#define f9_test pn_f9_test
// mac-struct

#define Hmac_state  pn_Hmac_state 
#define hmac_state pn_hmac_state
#define omac_state pn_omac_state
#define pmac_state pn_pmac_state
#define eax_state pn_eax_state
#define ocb_state pn_ocb_state
#define gcm_state pn_gcm_state
#define pelican_state pn_pelican_state
#define xcbc_state pn_xcbc_state
#define f9_state pn_f9_state
#define gcm_shift_table pn_gcm_shift_table

// math
#define ltc_math_descriptor  pn_ltc_math_descriptor 
#define ltc_mp pn_ltc_mp
#define ltm_desc pn_ltm_desc
#define tfm_desc pn_tfm_desc
#define gmp_desc pn_gmp_desc


// misc
#define base64_encode pn_base64_encode
#define base64_decode pn_base64_decode
#define zeromem pn_zeromem
#define crypt_fsa pn_crypt_fsa
#define crypt_build_settings pn_crypt_build_settings

// PK
#define rand_prime pn_rand_prime
#define rsa_make_key pn_rsa_make_key
#define rsa_exptmod pn_rsa_exptmod
#define rsa_free pn_rsa_free
#define rsa_encrypt_key_ex pn_rsa_encrypt_key_ex
#define rsa_decrypt_key_ex pn_rsa_decrypt_key_ex
#define rsa_sign_hash_ex pn_rsa_sign_hash_ex
#define rsa_verify_hash_ex pn_rsa_verify_hash_ex
#define rsa_export pn_rsa_export
#define rsa_import pn_rsa_import
#define katja_make_key pn_katja_make_key
#define katja_exptmod pn_katja_exptmod
#define katja_free pn_katja_free
#define katja_encrypt_key pn_katja_encrypt_key
#define katja_decrypt_key pn_katja_decrypt_key
#define katja_export pn_katja_export
#define katja_import pn_katja_import
#define ecc_test pn_ecc_test
#define ecc_sizes pn_ecc_sizes
#define ecc_get_size pn_ecc_get_size
#define ecc_make_key pn_ecc_make_key
#define ecc_make_key_ex pn_ecc_make_key_ex
#define ecc_free pn_ecc_free
#define ecc_export pn_ecc_export
#define ecc_import pn_ecc_import
#define ecc_import_ex pn_ecc_import_ex
#define ecc_ansi_x963_export pn_ecc_ansi_x963_export
#define ecc_ansi_x963_import pn_ecc_ansi_x963_import
#define ecc_ansi_x963_import_ex pn_ecc_ansi_x963_import_ex
#define ecc_shared_secret pn_ecc_shared_secret
#define ecc_encrypt_key pn_ecc_encrypt_key
#define ecc_decrypt_key pn_ecc_decrypt_key
#define ecc_sign_hash pn_ecc_sign_hash
#define ecc_verify_hash pn_ecc_verify_hash
#define ltc_ecc_new_point pn_ltc_ecc_new_point
#define ltc_ecc_del_point pn_ltc_ecc_del_point
#define ltc_ecc_is_valid_idx pn_ltc_ecc_is_valid_idx
#define ltc_ecc_projective_dbl_point pn_ltc_ecc_projective_dbl_point
#define ltc_ecc_projective_add_point pn_ltc_ecc_projective_add_point
#define ltc_ecc_fp_mulmod pn_ltc_ecc_fp_mulmod
#define ltc_ecc_fp_save_state pn_ltc_ecc_fp_save_state
#define ltc_ecc_fp_restore_state pn_ltc_ecc_fp_restore_state
#define ltc_ecc_fp_free pn_ltc_ecc_fp_free
#define ltc_ecc_fp_add_point pn_ltc_ecc_fp_add_point
#define ltc_ecc_fp_tablelock pn_ltc_ecc_fp_tablelock
#define ltc_ecc_mulmod pn_ltc_ecc_mulmod
#define ltc_ecc_mul2add pn_ltc_ecc_mul2add
#define ltc_ecc_fp_mul2add pn_ltc_ecc_fp_mul2add
#define ltc_ecc_map pn_ltc_ecc_map
#define dsa_make_key pn_dsa_make_key
#define dsa_free pn_dsa_free
#define dsa_sign_hash_raw pn_dsa_sign_hash_raw
#define dsa_sign_hash pn_dsa_sign_hash
#define dsa_verify_hash_raw pn_dsa_verify_hash_raw
#define dsa_verify_hash pn_dsa_verify_hash
#define dsa_encrypt_key pn_dsa_encrypt_key
#define dsa_decrypt_key pn_dsa_decrypt_key
#define dsa_import pn_dsa_import
#define dsa_export pn_dsa_export
#define dsa_verify_key pn_dsa_verify_key
#define dsa_shared_secret pn_dsa_shared_secret
#define der_encode_sequence_ex pn_der_encode_sequence_ex
#define der_decode_sequence_ex pn_der_decode_sequence_ex
#define der_length_sequence pn_der_length_sequence
#define der_encode_set pn_der_encode_set
#define der_encode_setof pn_der_encode_setof
#define der_encode_sequence_multi pn_der_encode_sequence_multi
#define der_decode_sequence_multi pn_der_decode_sequence_multi
#define der_decode_sequence_flexi pn_der_decode_sequence_flexi
#define der_free_sequence_flexi pn_der_free_sequence_flexi
#define der_sequence_free pn_der_sequence_free
#define der_length_boolean pn_der_length_boolean
#define der_encode_boolean pn_der_encode_boolean
#define der_decode_boolean pn_der_decode_boolean
#define der_encode_integer pn_der_encode_integer
#define der_decode_integer pn_der_decode_integer
#define der_length_integer pn_der_length_integer
#define der_decode_short_integer pn_der_decode_short_integer
#define der_encode_short_integer pn_der_encode_short_integer
#define der_length_short_integer pn_der_length_short_integer
#define der_encode_bit_string pn_der_encode_bit_string
#define der_decode_bit_string pn_der_decode_bit_string
#define der_length_bit_string pn_der_length_bit_string
#define der_encode_octet_string pn_der_encode_octet_string
#define der_decode_octet_string pn_der_decode_octet_string
#define der_length_octet_string pn_der_length_octet_string
#define der_encode_object_identifier pn_der_encode_object_identifier
#define der_decode_object_identifier pn_der_decode_object_identifier
#define der_length_object_identifier pn_der_length_object_identifier
#define der_object_identifier_bits pn_der_object_identifier_bits
#define der_encode_ia5_string pn_der_encode_ia5_string
#define der_decode_ia5_string pn_der_decode_ia5_string
#define der_length_ia5_string pn_der_length_ia5_string
#define der_ia5_char_encode pn_der_ia5_char_encode
#define der_ia5_value_decode pn_der_ia5_value_decode
#define der_encode_printable_string pn_der_encode_printable_string
#define der_decode_printable_string pn_der_decode_printable_string
#define der_length_printable_string pn_der_length_printable_string
#define der_printable_char_encode pn_der_printable_char_encode
#define der_printable_value_decode pn_der_printable_value_decode
#define der_encode_utf8_string pn_der_encode_utf8_string
#define der_decode_utf8_string pn_der_decode_utf8_string
#define der_utf8_charsize pn_der_utf8_charsize
#define der_length_utf8_string pn_der_length_utf8_string
#define der_decode_choice pn_der_decode_choice
#define der_encode_utctime pn_der_encode_utctime
#define der_decode_utctime pn_der_decode_utctime
#define der_length_utctime pn_der_length_utctime
//pk-struct
#define rsa_key pn_rsa_key
#define katja_key pn_katja_key
#define KAT_key  pn_KAT_key 
#define ltc_ecc_set_type pn_ltc_ecc_set_type
#define ecc_point pn_ecc_point
#define ecc_key pn_ecc_key
#define ltc_ecc_set_type  pn_ltc_ecc_set_type 
#define ltc_ecc_sets pn_ltc_ecc_sets
#define dsa_key pn_dsa_key
#define ltc_asn1_list_  pn_ltc_asn1_list_ 
#define ltc_utctime pn_ltc_utctime

//pkcs
#define pkcs_1_mgf1 pn_pkcs_1_mgf1
#define pkcs_1_i2osp pn_pkcs_1_i2osp
#define pkcs_1_os2ip pn_pkcs_1_os2ip
#define pkcs_1_v1_5_encode pn_pkcs_1_v1_5_encode
#define pkcs_1_v1_5_decode pn_pkcs_1_v1_5_decode
#define pkcs_1_oaep_encode pn_pkcs_1_oaep_encode
#define pkcs_1_oaep_decode pn_pkcs_1_oaep_decode
#define pkcs_1_pss_encode pn_pkcs_1_pss_encode
#define pkcs_1_pss_decode pn_pkcs_1_pss_decode
#define pkcs_5_alg1 pn_pkcs_5_alg1
#define pkcs_5_alg2 pn_pkcs_5_alg2

// pkcs-struct
#define ltc_pkcs_1_v1_5_blocks pn_ltc_pkcs_1_v1_5_blocks
#define ltc_pkcs_1_paddings pn_ltc_pkcs_1_paddings


//prng
#define yarrow_start pn_yarrow_start
#define yarrow_add_entropy pn_yarrow_add_entropy
#define yarrow_ready pn_yarrow_ready
#define yarrow_read pn_yarrow_read
#define yarrow_done pn_yarrow_done
#define yarrow_export pn_yarrow_export
#define yarrow_import pn_yarrow_import
#define yarrow_test pn_yarrow_test
#define fortuna_start pn_fortuna_start
#define fortuna_add_entropy pn_fortuna_add_entropy
#define fortuna_ready pn_fortuna_ready
#define fortuna_read pn_fortuna_read
#define fortuna_done pn_fortuna_done
#define fortuna_export pn_fortuna_export
#define fortuna_import pn_fortuna_import
#define fortuna_test pn_fortuna_test
#define rc4_start pn_rc4_start
#define rc4_add_entropy pn_rc4_add_entropy
#define rc4_ready pn_rc4_ready
#define rc4_read pn_rc4_read
#define rc4_done pn_rc4_done
#define rc4_export pn_rc4_export
#define rc4_import pn_rc4_import
#define rc4_test pn_rc4_test
#define sprng_start pn_sprng_start
#define sprng_add_entropy pn_sprng_add_entropy
#define sprng_ready pn_sprng_ready
#define sprng_read pn_sprng_read
#define sprng_done pn_sprng_done
#define sprng_export pn_sprng_export
#define sprng_import pn_sprng_import
#define sprng_test pn_sprng_test
#define sober128_start pn_sober128_start
#define sober128_add_entropy pn_sober128_add_entropy
#define sober128_ready pn_sober128_ready
#define sober128_read pn_sober128_read
#define sober128_done pn_sober128_done
#define sober128_export pn_sober128_export
#define sober128_import pn_sober128_import
#define sober128_test pn_sober128_test
#define find_prng pn_find_prng
#define register_prng pn_register_prng
#define unregister_prng pn_unregister_prng
#define prng_is_valid pn_prng_is_valid
#define rng_get_bytes pn_rng_get_bytes
#define rng_make_prng pn_rng_make_prng

// prng-struct
#define yarrow_prng  pn_yarrow_prng 
#define rc4_prng  pn_rc4_prng 
#define fortuna_prng  pn_fortuna_prng 
#define sober128_prng  pn_sober128_prng 
#define Prng_state  pn_Prng_state 
#define prng_state pn_prng_state
#define ltc_prng_descriptor  pn_ltc_prng_descriptor 
#define prng_descriptor pn_prng_descriptor
#define yarrow_desc pn_yarrow_desc
#define fortuna_desc pn_fortuna_desc
#define rc4_desc pn_rc4_desc
#define sprng_desc pn_sprng_desc
#define sober128_desc pn_sober128_desc
#define ltc_prng_mutex pn_ltc_prng_mutex

// c file
#define ltc_ecc_fp_lock pn_ltc_ecc_fp_lock
#define safer_ebox pn_safer_ebox
#define safer_lbox pn_safer_lbox
