//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Nettention.Proud {

public enum FastEncryptLevel {
  FastEncryptLevel_Low = 512,
  FastEncryptLevel_Middle = 1024,
  FastEncryptLevel_High = 2048
}

}
