
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "ChatS2C_common.h"
namespace ChatS2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_ShowChat,
               
		Rmi_UserList_Add,
               
		Rmi_UserList_Remove,
	};

	int g_RmiIDListCount = 3;

}





