
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "S2C_common.h"
namespace LicenseS2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_NotifyAuthentication,
               
		Rmi_NotifyAuthenticationComment,
               
		Rmi_NotifyRecordServerInfo,
	};

	int g_RmiIDListCount = 3;

}


